# Generated by Django 3.2.12 on 2022-03-16 21:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twitter', models.URLField(default='https://itsmurgor=09')),
                ('reddit', models.URLField(default='https://itsmurgor=09')),
                ('facebook', models.URLField(default='https://itsmurgor=09')),
                ('instagram', models.URLField(default='https://itsmurgor=09')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('comment', models.TextField(max_length=2000)),
                ('date', models.DateField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.blog')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
